wip

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,7 +28,30 @@ jobs:
 
             gh_api_url="https://api.github.com/repos/nats-io/nats-server/releases"
 
-            response=$(curl -s $gh_api_url/latest)
+            retry_curl() {
+                local url=$1
+                local max_retries=5
+                local retry_delay=10
+                local attempt=1
+                local response=""
+
+                while [ $attempt -le $max_retries ]; do
+                    response=$(curl -s $url)
+                    if [ $? -eq 0 ]; then
+                        echo "$response"
+                        return 0
+                    else
+                        echo "Attempt $attempt failed, retrying in $retry_delay seconds..."
+                        sleep $retry_delay
+                        attempt=$((attempt + 1))
+                    fi
+                done
+
+                echo "Failed to fetch URL after $max_retries attempts"
+                return 1
+            }
+
+            response=$(retry_curl $gh_api_url/latest)
             # echo "API Response: $response"
             branch=$(echo $response | jq -r .tag_name)
             # echo "Determined branch: $branch"
