wip

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,7 +30,78 @@ jobs:
         run: dotnet restore
 
       - name: Build
-        run: dotnet build --no-restore
+        run: dotnet build --no-restore -p:SignAssembly=false
 
       - name: Test
-        run: dotnet test --no-build
+        run: dotnet test --no-build --logger:"console;verbosity=normal" --collect:"XPlat Code Coverage" --settings Default.runsettings
+
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@v4.0.1
+        with:
+            token: ${{ secrets.CODECOV_TOKEN }}
+
+      - name: Check Native AOT
+        shell: bash
+        run: |
+            echo ">> Set up for AOT compilation..."
+            export exe_file=NATS.Jwt.CheckNativeAot
+            export exe_type=ELF
+            export dotnet_runtime_id=linux-x64
+
+            echo ">> Checking OS..."
+            if [ "${{ matrix.os }}" = "windows-latest" ]; then
+              export exe_file=NATS.Jwt.CheckNativeAot.exe
+              export exe_type=PE32
+              export dotnet_runtime_id=win-x64
+            elif [ "${{ matrix.os }}" = "macos-latest" ]; then
+              export dotnet_runtime_id=osx-x64
+              export exe_type=Mach-O
+            fi
+
+            echo ">> Publishing..."
+            cd NATS.Jwt.CheckNativeAot
+            rm -rf bin obj
+            dotnet publish -r $dotnet_runtime_id -c Release -o dist | tee output.txt
+
+            echo ">> Checking for warnings..."
+            grep -i warning output.txt && exit 1
+
+            echo ">> Executable sanity checks..."
+            cd dist
+            ls -lh
+
+            echo ">> Executable is of type $exe_type..."
+            file $exe_file
+            file $exe_file | grep $exe_type || exit 1
+
+            echo ">> Executable size checks..."
+            # Can't be less than a meg and not more than 10 megs.
+            # Fairly arbitrary, but we want to make sure executable size
+            # is reasonable so we can be somewhat sure AOT compilation
+            # happened correctly.
+            export filesize=0
+
+            if [ "${{ matrix.os }}" = "windows-latest" ]; then
+              export filesize=$(stat -c %s $exe_file)
+            elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
+              export filesize=$(stat -c %s $exe_file)
+            elif [ "${{ matrix.os }}" = "macos-latest" ]; then
+              export filesize=$(stat -f %z $exe_file)
+            fi
+
+            echo ">> File size: $filesize bytes"
+            if [ $filesize -lt 1048576 ]; then
+              echo ">> Error: File is less than 1MB."
+              exit 1
+            fi
+            if [ $filesize -gt 10485760 ]; then
+              echo ">> Error: File is more than 10MB."
+              exit 1
+            fi
+            echo ">> File size is within acceptable range."
+
+            echo ">> Running executable..."
+            ./$exe_file | tee | grep PASS || exit 1
+
+            echo ">> Run complete."
+
